### ISSUE TITLE
Consider Citron for parsing

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#12]
I found [this](https://github.com/roop/citron) to be a pleasure to use and it
reduced the amount of code in my project considerably over the corresponding
hand-coded parser.

**Comment by kyouko-taiga** [comment]
The current implementation uses a custom data structure as it parses declarations to configure scopes (i.e., assign `Decl.parentDeclSpace`). Would it be possible to reproduce that behavior with Citron?

I'm also a little concerned about error messages. The current implementation purposely parses a superset of Val's actual grammar so that the parser can identify common errors (e.g., missing annotation in a parameter declaration, method qualifier on free function, etc.). How would you handle this kind of errors with Citron?
