### ISSUE TITLE
Consider `origin` => `locus` or `sourceLocus`

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#124]
I know we could paint this shed 1000x and this is a super-low priority, but I had this insight while working on some other code and trying to figure out the names.  I was already using `origin` to mean the _start_ of a source range, and origin really does connote “where it started,” so settled on `locus`. Thoughts on a similar change in Val?

**Comment by kyouko-taiga** [comment]
The rationale makes sense, but note that I doubt any non-native English speaker is familiar with the word "locus". I certainly never heard of it before. So I worry it would not be immediately clear to many developers what `someNode.locus` or even `someNode.sourceLocus`. What about `locations`/`sourceLocations` (in plural)?

I think that property is tricky to name. Even documenting its meaning concisely is challenging.

Maybe the issue is that the property is part of a different abstraction that we're trying to shove into a node, that abstraction being the node's source representation. I guess it would make sense to have `someNode.sourceRepresentation.startLocation`/`endLocation`.

**Comment by dabrahams** [comment]
Your point about recognizability is well-taken.  What about simply `source` or `text`?  That range represents the source code.  If we are worried about that being confusing, we could use `sourceRegion` but the fact that it's a region of source is captured in the type.

I'd rather not use something like `someNode.sourceRepresentation.startLocation/endLocation` when we have a first-class `Range` abstraction in the stdlib.

**Comment by kyouko-taiga** [comment]
`test` seems very appropriate to me.
