### ISSUE TITLE
What are the effects on the AST if parsing fails?

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#212]
In order to avoid copying the AST each time it is parsed by routines I am writing (and documenting), I need to know whether the AST is (logically) modified in that case, and if so, whether it is left in a valid state.  I don't _think_ that information is documented.

**Comment by kyouko-taiga** [comment]
The AST is left intact if parsing failed. Here is the relevant [line](https://github.com/val-lang/val/blob/f98d4016839afad7b30564136307defbdae9fc4b/Sources/FrontEnd/Parse/Parser.swift#L75).

**Comment by dabrahams** [comment]
Ok, I was going to say that should be documented but I doubt we should enshrine that strong guarantee, at least not with that strategy. IIUC that’s tantamount to a premature copy/swap which makes parsing N source files an O(N^2) operation. Sent from my iPhoneOn Jan 7, 2023, at 3:19 AM, Dimi Racordon ***@***.***> wrote:﻿
The AST is left intact if parsing failed. Here is the relevant line.

**Comment by kyouko-taiga** [comment]
What would be your preferred behavior? I suppose it's the strong guarantee, right?

The AST you give to `Parser.parse(_:into:in)` is used as the collection in which new nodes are being inserted. If parsing failed, then it's possible this collection (i.e., the node array in the AST) will have been extended. However, the parser never _modifies_ anything already inside the AST except the module passed as the second argument ([relevant line](https://github.com/val-lang/val/blob/02bd51c57ece12b19713ada75a0a2f7e2616d318/Sources/FrontEnd/Parse/Parser.swift#L62)).

If we excluded nodes that aren't contained in a module from the value of an AST, then I believe the strong guarantee would be relatively cheap to uphold. That's because we only need to copy/swap the module in which new declarations are being inserted, which is essentially an array of node IDs.

**Comment by dabrahams** [comment]
> On Jan 8, 2023, at 3:04 AM, Dimi Racordon ***@***.***> wrote:
> 
> What would be your preferred behavior?
> 
I appreciate the consideration, but that's the wrong question to ask ;-)

One should always ask what is the strongest guarantee that falls out naturally from an efficient implementation.
> I suppose it's the strong guarantee, right?
> 
Every time someone makes that supposition, I fear I’ve named the guarantees badly.  Remember, giving the strong guarantee for individual operation is neither always necessary (because the mutated data is usually going to be discarded in the event of an error) nor always sufficient (because the guarantee doesn’t compose) to ensure correct error handling.
> The AST you give to Parser.parse(_:into:in) is used as the collection in which new nodes are being inserted. If parsing failed, then it's possible this collection (i.e., the node array in the AST) will have been extended. However, the parser never modifies anything already inside the AST except the module passed as the second argument (relevant line <https://github.com/val-lang/val/blob/02bd51c57ece12b19713ada75a0a2f7e2616d318/Sources/FrontEnd/Parse/Parser.swift#L62>).
> 
> If we excluded nodes that aren't contained in a module from the value of an AST, then I believe the strong guarantee would be relatively cheap to uphold. That's because we only need to copy/swap the module in which new declarations are being inserted, which is essentially an array of node IDs.
> 
Ah,  I didn’t realize each module had its own array of nodes!  In that case, what you’re doing there is probably just fine, performance-wise, and promising the strong guarantee is fine.  In a program with many thousands of modules, one might want to choose a persistent data structure for the modules, but we can cross that bridge when we come to it.

Thanks for talking me through this.

**Comment by dabrahams** [comment]
As I think about it more, it seems like it could make sense to have an ASTModule type, build those in the parser, and simply insert them into the AST when they're built?

**Comment by kyouko-taiga** [comment]
Yes, that sounds like a good idea.

**Comment by kyouko-taiga** [comment]
Issue has been resolved. The suggested strategy is the one currently implemented.
