### ISSUE TITLE
Parser: `expect` seems surprisingly API'd and like a maintenance/boilerplate problem

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#217]
Maybe I'm misunderstanding here, but it looks like `expect(something, parser)`, to my surprise, doesn't peek ahead to make sure `something` is next in the input before applying `parser`, but instead applies `parser` unconditionally and only if it fails reports that `something` was expected.  

Seems to me there's no need to separate parser state from parsers, but even if there is,
`parser.parse(in: &state, orReportExpected: something)` would make more sense.

The maintenance/boilerplate problem I see is that the parser itself knows exactly what it expects first, but instead we're asking the caller to supply that.

**Comment by kyouko-taiga** [comment]
> to my surprise, [`expect`] doesn't peak ahead to make sure `something` is next

"Peaking" only works on token. I wanted a method to tentatively parse an arbitrary construct and generate the appropriate message on failure (see below). I agree that this function could be defined as a parser rather than a method of `state`.

> Seems to me there's no need to separate parser state from parsers

Higher-order and mutating functions do not work well together in Swift. In an ideal world, `state` would `self` and we would write parsers that way:

```swift
struct Parser {
  mutating func parseFoo() throws -> Foo? { ... }
  ...
}
```

The problem with this approach is that it makes it difficult to use `parseFoo` as an argument to a higher order function that's also mutating the receiver. For example:

```swift
struct Parser {
  mutating func parseList<T>(_ element: () throws -> T?) throws -> [T] { ... }

  mutating func parseFoo() throws -> Int? { ... }
  mutating func parseFooList() throws -> [Int] {
    try parseList(parseFoo) // error: escaping autoclosure captures 'inout' parameter 'self'
  }
}
```

We can get around this problem by manually creating closures that apply the mutating methods:

```swift
extension Parser {
  mutating func parseList<T>(_ element: (inout Parser) throws -> T?) throws -> [T] {
    var results: [T] = []
    while let t = try element(&self) { results.append(t) }
    return results
  }

  mutating func parseFoo() throws -> Int? { ... }
  mutating func parseFooList() throws -> [Int] {
    try parseList({ try $0.parseFoo() })
  }
}
```

Maybe that's simpler? I don't know. What's sure is that this approach won't work with the code that still use Durian (the parser combinator library).

> but even if there is, `parser.parse(in: &state, orReportExpected: something)` would make more sense.

Works for me.

> The maintenance/boilerplate problem I see is that the parser itself knows exactly what it expects first, but instead we're asking the caller to supply that.

The goal of this method is to eliminate this pattern from the parsers:

```swift
guard let foo = someParser.parse(&state) else {
  throw ...
}
```

This method has let me transform this guard statements into one-liners in many places, like [here](https://github.com/val-lang/val/blob/02bd51c57ece12b19713ada75a0a2f7e2616d318/Sources/FrontEnd/Parse/Parser.swift#L1022).

**Comment by kyouko-taiga** [comment]
Notice that if parse returns a soft failure (i.e., `nil`), it won't throw anything. That's because all parsers can return `nil` if they didn't consume anything from the stream.

`expect` is used to say "I expect this thing, even if you can't consume any token, because I don't have any alternative"

**Comment by dabrahams** [comment]
> On Jan 9, 2023, at 11:35 AM, Dimi Racordon ***@***.***> wrote:
> 
> 
> Notice that if parse returns a soft failure (i.e., nil), it won't throw anything. That's because all parsers can return nil if they didn't consume anything from the stream.
> 
Thanks for the explanation.

I guess I’m also unclear on the significance of the hard vs. soft distinction. “Didn’t consume anything” really seems unimportant  when backtracking is available, and the cost of setting up backtracking for something that turns out not to consume anything (presumably leaving the parser state intact) is probably negligible.
> expect is used to say "I expect this thing, even if you can't consume any token, because I don't have any alternative”
> 
Yeah, I understand.

**Comment by kyouko-taiga** [comment]
> I guess I’m also unclear on the significance of the hard vs. soft distinction. “Didn’t consume anything” really seems unimportant  when backtracking is available, and the cost of setting up backtracking for something that turns out not to consume anything (presumably leaving the parser state intact) is probably negligible.

It's not about performance. It's about committing the parser so we avoid backtracking all the way to the latest alternative when there's a parse error.

Consider the following rules:
```
A ::= 'x' 'x' 'x' 'x' 'y'
B ::= 'z'
C ::= A | B
```
Now imagine we have the following input: `xxxxz` and try to recognize it with `C`.

If we allowed the parser to backtrack on any kind of failure, we would eventually fail while trying to apply `B`. That's not technically incorrect, but that makes issuing diagnostics much harder because now the parser is looking at the first `x` so all we can do is something like

> expected `z` but found `x`.

Before we backtracked, we had almost completely recognized `A` and would have been able to issue a very precise diagnostic.

So the question is: when should `C` decide to give up on parsing `A` and try `B` instead?

That's what soft/hard failures are answering. A hard failure only occur once a parser has recognized some prefix, at which points it "commits" to its parse. We can opt-in backtracking explicitly to recover from hard failures, but in general that's not necessary because most of Val's syntax is LL1. So soft failures are enough to select the right sub-parser.

**Comment by dabrahams** [comment]
> Before we backtracked, we had almost completely recognized A and would have been able to issue a very precise diagnostic.

I think there's a better way to handle all this… related to [this comment](https://val-qs97696.slack.com/archives/C01MEFN3TGE/p1673209251797449)

**Comment by kyouko-taiga** [comment]
Closing this as the original question seems to have been answered.
