### ISSUE TITLE
Cannot use infix operators without spaces

### ISSUE THREAD

**Issue by lucteo** [val-lang/val#278]
The following Val code:
```
  var a = 5
  var b = 7
  let _ = a+b
```
fails to compile with the following errors:
```
TestCases/CXX/Expr/InfixOperators.val:12: error: -[ValTests.CXXTests testTranspiler] : unexpected diagnostic: 'unused result of type 'Int''
TestCases/CXX/Expr/InfixOperators.val:12: error: -[ValTests.CXXTests testTranspiler] : unexpected diagnostic: 'type 'Int' has no member 'postfix+''
```

Adding spaces around the `+` operator seems to make the compiler work.

**Comment by kyouko-taiga** [comment]
Errors are wrong, but infix operators always require space on both sides.

**Comment by lucteo** [comment]
Ok, makes sense.

To me, this is a limitation that users will complain about. There are a lot of users that don't like to put spaces around infix operators (or, at least to some of the operators). E.g., people would want to write `a + b*c`.

**Comment by kyouko-taiga** [comment]
The problem is that allowing infix operators without spaces makes this kind of expressions ambiguous:  `a +a`. I understand the worry but Swift shows it can be pulled off, as it has almost the same limitation.

**Comment by dabrahams** [comment]
I don’t see how a +a could ever be ambiguous, since we don’t allow expressions next to one another with no intervening sigil.

Regardless, we could (and probably should) just do what Swift does and accept infix operators as long as the existence of space on either side is consistent, eg. a + b or a+b but not a+ b.  To me, anything else seems like we’re being needlessly “innovative."

**Comment by lucteo** [comment]
I personally find it "natural" to have Scala-like operators. I've used an adapted version of these in Sparrow, and I really liked the results. See https://www.researchgate.net/profile/Lucian-Teodorescu/publication/276154942_FLEXIBLE_OPERATORS_IN_SPARROW/links/57134f2e08ae39beb87a8a07/FLEXIBLE-OPERATORS-IN-SPARROW.pdf
(in there the flexibility was probably too much, but you don't need to get that far off).

The parsing rules are simple. An expression like: `o1 O1 o2 O2 o3 O3 o4 O4` will be parsed as following:
* be default, all terms on odd positions are operands (lowercase `o`); the even-positions are operators (upper case `O`).
* if at an even position one can find an string of symbols, that would be treated as a prefix operator, and the whole array of terms will be shifted/reconsidered (odds switch places with evens).
* if the sequence ends with an operator, that would be treated as a postfix operator

Note that regular identifiers can also be operators.

For example a problem like:
`What is the root mean square of the lengths of all the Collatz sequences up the first one that has a length greater than or equal to 500?`
can be solved in one line as:
```
var res = (1..) map \collatzSeq map \rangeSize takeWhile (fun s = s < 500) rootMeanSquare;
```
Ignoring the `\` (function reference) and lambda syntax, the code reads naturally from left to right. The code shows only terms from the problem description, and it's actually smaller than the English text.

**Comment by kyouko-taiga** [comment]
> I don’t see how a +a could ever be ambiguous, since we don’t allow expressions next to one another with no intervening sigil.

That rule is in general not so easy to enforce and requires many tricks on the grammar rules.

But let's not get drawn into the details. I don't want to be innovative, but I'm very opinionated about operators. I also don't see a reason to add complexity to our grammar only to handle marginal uses of operators without spaces, which arguably make it harder to tell if an operator is infix or not. I'm also willing to defend my position against disappointed users.

I see much, much more `a + a` than `a+a` in Swift or other languages so I don't think the rule goes against common wisdom. We can also imagine that a future version of our parse can emit fix-its.

> I personally find it "natural" to have Scala-like operators.

We discussed that idea and eventually decided to say no. Besides, there are already many subtle rules that need to be upheld to make operators work because they can appear in so many contexts, due to the whole "types are expressions" thing. I don't think it's worth over-engineering them any further, at least until we reach concrete limitations when we'll write code.
