### ISSUE TITLE
Consider `Typed<ModuleDecl>` instead of `ModuleDecl.Typed`

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#286]
The word order just makes more sense.

```swift
typealias Typed<T> = TypedNode<NodeID<T>>
```

**Comment by lucteo** [comment]
I can look at this, but I want to get some more progress on the transpiler first.

**Comment by kyouko-taiga** [comment]
Would Using `TypedNode` be that bad? The alias seems unnecessary. Many things can be typed, like a program.

There are many places in the code where `FooDecl.Typed(d)!` could be replaced by just `TypedNode(d)!`, which I think is a better improvement. WDYAL?

**Comment by dabrahams** [comment]
What's the harm, exactly?

> There are many places in the code where FooDecl.Typed(d)! could be replaced by just TypedNode(d)! or even .init(d)!, which I think is a better improvement. WDYAL?

My default would be to agree that those instances should be changed, but I'd like to see the examples before I know for sure.

**Comment by kyouko-taiga** [comment]
> To me these look like a job for prefix ^

_I'll make all examples with the untyped API because I'm more familiar with it. The same problems will occur on the typed API._

I worry a little about adding too many overloads for `prefix^`. One problem that's stopped me so far is that given a concrete ID, we don't know how much erasure we want. For example, the following properties hold:
- `NodeID<FunctionDecl> <: AnyDeclID`
- `NodeID<FunctionDecl> <: AnyScopeID`
- `NodeID<FunctionDecl> <: AnyNodeID`
- `AnyScopeID <: AnyScopeID`

That means we'll need three overloads of `prefix^` and only use the operator in contexts sufficiently constrained to infer the return type. So no `let x = ^someID` int he general case. If we have to write `let x: AnyDeclID = ^someID` we didn't improve on the status quo.

**Comment by kyouko-taiga** [comment]
> I don’t understand how the repetition (of which the labels are a part) leads you to like the labels.

Assume we'd write visitors like this:
```swift
struct visitor {
  func visit(_ x: Erased) { ... }
  func visit(_ x: ConcreteA) { ... }
  func visit(_ x: ConcreteB) { ... }
}
```

Now in the erased base, we'd have to cast `x` at each call site:
```swift
func visit(_ x: Erased) {
  switch x.kind {
  case ConcreteA.self:
    visit(ConcreteA(x)!)
  case ConcreteB.self:
    visit(ConcreteB(x)!)
  default:
    unreachable()
  }
}
```

The labels solve two issues:
1. The result of dispatch is unambiguous at call site because determining where `visit(x)` goes requires to know the type of `x`. In my experience, it's easy to get mistaken.
2. We don't need to repeat the name of the type in each case because it's already encoded in the label. We can write `visit(a: .init(x))`.

**Comment by kyouko-taiga** [comment]
> Is this struct actually an ID as the name implies, though?  I don’t think so, or the following declaration wouldn’t make sense.  It can’t be both a node and a node ID, at least.

Good observation. I retract my second suggestion.

I'm still bothered by the fact that `Typed<T>` claims `T: Node` but won't stay in the way if the majority wants to go ahead with this change.

**Comment by dabrahams** [comment]
I have no opinion one way or another, especially now that you've pointed out those existing opportunities for simplification.  I think we should do those first.

I unders  tand point 1.It's point 2 I don't understand.  `visit(concreteA: .init(x)!)` repeats a type name just as much as `visit(ConcreteA(x)!)` does, and the latter is shorter.

**Comment by kyouko-taiga** [comment]
My presentation was not ideal.

My reasoning is based on the fact that I assume labels are desirable (because of (1)). So I'm observing instances of `visit(concreteA: ConcreteA(x)!)` and saying the labels give the opportunity to simplify as `visit(concreteA: .init(x)!)`.

**Comment by kyouko-taiga** [comment]
No longer relevant.
